version: "3.3"

services:
    postgres:
      image: postgres:11
      volumes:
        - ./data/db:/var/lib/postgresql/data
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=postgres
    # web:
    #   build: ./server
    #   command: python main.py
    #   volumes:
    #     - ./server:/code
    #   ports:
    #     - "8000:8000"
    #   environment:
    #     - MLMONITOR_DATABASE_URI=postgresql://postgres:postgres@postgres/postgres
    #   depends_on:
    #     - postgres
    web:
      build: .
      command: mlmonitoring --host 0.0.0.0 --port 8000
      ports:
        - "8000:8000"
      environment:
        - MLMONITOR_DATABASE_URI=postgresql://postgres:postgres@postgres/postgres
      depends_on:
        - postgres
    metabase:
      image: metabase/metabase
      restart: always
      ports:
        - 3001:3000
      volumes:
        # declare your mount volume /host/dir:/container/dir
        - /home/app/metabase-data:/metabase-data
      environment:
        MB_DB_TYPE: postgres
        MB_DB_DBNAME: postgres
        MB_DB_PORT: 5432
        MB_DB_USER: postgres
        MB_DB_PASS: postgres
        MB_DB_HOST: postgres
      depends_on:
        - postgres
      links:
        - postgres
