version: "3.3"

services:
    postgres:
      image: postgres:11
      volumes:
        - ./data/db:/var/lib/postgresql/data
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=postgres
    web:
      build: ./server
      command: python main.py
      volumes:
        - ./server:/code
      ports:
        - "8000:8000"
      environment:
        - MLMONITOR_DATABASE_URI=postgresql://postgres:postgres@postgres/postgres
      depends_on:
        - postgres